// Generated by https://quicktype.io

import { message } from "./discord";

export interface Interaction {
    type:       number;
    token:      string;
    member:     Member;
    id:         string;
    guild_id:   string;
    data:       Data;
    channel_id: string;
}

export interface Data {
    options: Option[];
    name:    string;
    id:      string;
}

export interface Option {
    name:  string;
    value: string;
}

export interface Member {
    user:          User;
    roles:         string[];
    premium_since: null;
    permissions:   string;
    pending:       boolean;
    nick:          null;
    mute:          boolean;
    joined_at:     string;
    is_pending:    boolean;
    deaf:          boolean;
}

export interface User {
    id:            string;
    username:      string;
    avatar:        string;
    discriminator: string;
    public_flags:  number;
}

// ! Generated by https://quicktype.io

export interface ButtonInteraction {
    version:        number;
    type:           number;
    token:          string;
    message:        message;
    member:         Member;
    id:             string;
    guild_id:       string;
    data:           ButtonData;
    channel_id:     string;
    application_id: string;
}

export interface ButtonData {
    custom_id:      string;
    component_type: number;
}

export interface MessageComponent {
    type:       number;
    components: ComponentComponent[];
}

export interface ComponentComponent {
    type:      number;
    label:     string;
    style:     number;
    custom_id: string;
}
